apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-web-ing
  namespace: portfolio
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: portfolio.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-web-svc
                port:
                  number: 80

