apiVersion: v1
kind: Service
metadata:
  name: portfolio-web-svc
  namespace: portfolio
spec:
  type: ClusterIP
  selector:
    app: portfolio-web
  ports:
    - name: http
      port: 80
      targetPort: 3000

